version: '3'
services:
  app:
    container_name: claim-app
    restart: always
    build: .
    ports:
      - '3030:3000'
    external_links:
      - mongo
    environment:
      - POLICY_SERVICE=google.com
      - BILLING_SERVICE=google.com
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'